### ISSUE TITLE
CI Failed randomly on `Build_image`

### ISSUE THREAD

**Issue by alallema** [meilisearch/meilisearch-aws#44]
**Description**
The CI failed during its automatic launch. (timeout)

**Expected behavior**
Ci should pass every time

**Current behavior**
An error is raised [here an example](https://github.com/meilisearch/meilisearch-aws/runs/3161353714?check_suite_focus=true)

**Screenshots or Logs**
```
Run python3 tools/build_image.py $IMAGE_NAME
  python3 tools/build_image.py $IMAGE_NAME
  shell: /usr/bin/bash -e {0}
  env:
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    pythonLocation: /opt/hostedtoolcache/Python/3.7.11/x64
    IMAGE_NAME: meilisearch_aws_ci_test_26-07-2021-12-17-40
Creating AWS EC2 instance
   Instance created. ID: i-0f79824cebb7d5d21
Waiting for AWS EC2 instance state to be "running"
   Instance state: running
   Instance IP: None
Waiting for MeiliSearch health check (may take a few minutes: config and reboot)
   Timeout waiting for health check
   Terminating instance i-0f79824cebb7d5d21
ENDING PROCESS WITH EXIT CODE 1
Error: Process completed with exit code 1.
```

**Comment by sanders41** [comment]
I'm guessing the problem is the IP address: `Instance IP: None`

The health check uses the ip address [here](https://github.com/meilisearch/meilisearch-aws/blob/0dd2167868032f61c1b6e5c2af8ce8c9168899a4/tools/utils.py#L34) so if it is `None` that would cause the problem. Possibly either sleeping a second after the instance says it is running or calling `reload` on the instance would help?

Because there is a [pass](https://github.com/meilisearch/meilisearch-aws/blob/0dd2167868032f61c1b6e5c2af8ce8c9168899a4/tools/utils.py#L38) on all exceptions in the health check it will be hard to verify the root cause. I'm not a boto3/EC2 expert, is there a specific expected exception that would be returned if MeiliSearch isn't ready yet that could be passed on? Then other exceptions could raise since it would mean something else is wrong and the health check will never be successful.

If that isn't an option maybe something along these lines could be an option so you can see the cause of the issue.

```py
def wait_for_health_check(instance, timeout_seconds=None):
    start_time = datetime.datetime.now()
    while timeout_seconds is None \
            or check_timeout(start_time, timeout_seconds) is not STATUS_TIMEOUT:
        try:
            resp = requests.get(
                'http://{}/health'.format(instance.public_ip_address))
            if resp.status_code >= 200 and resp.status_code < 300:
                return STATUS_OK
        except Exception as err:
            print(f'MeiliSearch is not yet ready, retrying. Exception: {err}')
        time.sleep(1)
    return STATUS_TIMEOUT
```

**Comment by alallema** [comment]
Hi @sanders41 !
I think that while waiting to find out where the problem comes from it can be a good option.
Thanks for your advice

**Comment by curquiza** [comment]
Checked with @alallema, it seems to be solved :)
